### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by NaathySz** [Mbk10201/Discord_loggerv2#2]
Great plugin, using on my server since its start! 

Can you do case drops too? to send the nickname, case name, current value, and if possible, case photo. I see an plugin like this, but not public

Hope you do it
Good job!

**Comment by Mbk10201** [comment]
Hey thanks, What do you mean by case opening ? opening the case of the game ? or the plugin that you can open cases in server ?

**Comment by NaathySz** [comment]
> Hey thanks, What do you mean by case opening ? opening the case of the game ? or the plugin that you can open cases in server ?

Not open, but drops
Like.. if i drop some case, it go to discord with infos about the drop

Like:
"Player X dropped case X, price X, etc.."

**Comment by Mbk10201** [comment]
alright, i will do it on my free time

**Comment by NaathySz** [comment]
https://prnt.sc/_R_7MwQeoqd3 

here a print for example

**Comment by Mbk10201** [comment]
> https://prnt.sc/_R_7MwQeoqd3
> 
> here a print for example

Yeah thanks, if you have others requests dont hesitate to add me on discord: MBK#2443
